name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # prevent from running on forks
    if: github.repository_owner == 'restatedev'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
      - run: pnpm install --frozen-lockfile
      - run: pnpm verify
